### ISSUE TITLE
Component type is inferred as any

### ISSUE THREAD

**Issue by Stadly** [sveltejs/eslint-plugin-svelte#717] opened 2024-03-21 09:12 UTC
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.57.0

### What version of `eslint-plugin-svelte` are you using?

2.35.1

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: ['plugin:@typescript-eslint/recommended-type-checked'],
  overrides: [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        project: true,
        tsconfigRootDir: __dirname,
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module',
    extraFileExtensions: ['.svelte'],
    project: ['tsconfig.json', 'tsconfig.node.json'],
    tsconfigRootDir: __dirname,
  },
};
```
</details>

```svelte
<!-- Hidable.svelte -->
<script lang="ts">
    export let hidden = true;
    export const show = () => {
        hidden = false;
    };
</script>

{#if !hidden}
    <slot />
{/if}


<!-- ShowOnMount.svelte -->
<script lang="ts">
    import Hidable from "$lib/Hidable.svelte";
    import { onMount } from "svelte";

    let hidable: Hidable | undefined;
    onMount(() => {
        hidable?.show();
    });
</script>

<Hidable bind:this={hidable}>
    <slot />
</Hidable>
```

### What did you expect to happen?

No errors.

### What actually happened?

```
/workspaces/reproduction/src/lib/ShowOnMount.svelte
  7:9  error  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call
```

Note: If you look at `ShowOnMount.ts` in the reproduction, you'll see that it generates the same error, so the issue does not only occur in `.svelte` files.

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/Stadly/reproduction/tree/eslint-plugin-svelte/component-type-is-any

**Comment by ota-meshi** [comment] 2024-03-21 10:47
Duplicate of #298

**Closed by ota-meshi** 2024-03-21 10:47 UTC
