### ISSUE TITLE
Snippets that use a `() => void` type break eslint when using typescript

### ISSUE THREAD

**Issue by AlbertMarashi** [sveltejs/eslint-plugin-svelte#904] opened 2024-09-19 08:59 UTC
### Describe the bug

There's a weird eslint bug with parsing snippets that contain `() => void`, even if it is commented out.

### Reproduction

```svelte
<script lang="ts">

</script>

{#snippet editor_button(foo: {
    // onclick: () => void,
})}

{/snippet}
```
`Parsing error: '}' expected.eslint`

---

```svelte
<script lang="ts">

</script>

{#snippet editor_button(foo: {
    onclick: () => void,
})}

{/snippet}
```

`Parsing error: '=>' expected.eslint`

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 108.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.7.0 - ~/Library/pnpm/pnpm
    bun: 1.1.18 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.2
  npmPackages:
    svelte: 5.0.0-next.244 => 5.0.0-next.244
```

### Severity

blocking upgrade

**Comment by ota-meshi** [comment] 2024-11-03 23:13
Duplicate of #872 
It has already been fixed.

**Closed by ota-meshi** 2024-11-03 23:13 UTC
